# Generated by Django 5.1.1 on 2024-09-14 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('EQ_M', 'Equipment model'), ('EN_M', 'Engine model'), ('TR_M', 'Transmission model'), ('DA_M', 'Drive axle model'), ('CB_M', 'Controlled bridge model'), ('MN_T', 'Maintenance type'), ('FAIL', 'Failure node'), ('RE_M', 'Recovery method')], max_length=4)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=128, unique=True, verbose_name='Заводской номер')),
                ('engine_serial_number', models.CharField(max_length=128, verbose_name='Заводской номер двигателя')),
                ('transmission_serial_number', models.CharField(max_length=128, verbose_name='Заводской номер трансмиссии')),
                ('drive_axle_serial_number', models.CharField(max_length=128, verbose_name='Заводской номер ведущего моста')),
                ('controlled_bridge_serial_number', models.CharField(max_length=128, verbose_name='Заводской номер управляемого моста')),
                ('supply_contract_number_date', models.CharField(max_length=128, verbose_name='Договор поставки номер, дата')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=256, verbose_name='Грузополучатель')),
                ('delivery_address', models.CharField(max_length=256, verbose_name='Адрес поставки')),
                ('additional_equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'C'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('controlled_bridge_model', models.ForeignKey(limit_choices_to={'entity': 'CB_M'}, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_bridge_machines', to='machines.catalog', verbose_name='Модель управляемого моста')),
                ('drive_axle_model', models.ForeignKey(limit_choices_to={'entity': 'DA_M'}, on_delete=django.db.models.deletion.PROTECT, related_name='drive_axle_machines', to='machines.catalog', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(limit_choices_to={'entity': 'EN_M'}, on_delete=django.db.models.deletion.PROTECT, related_name='engine_machines', to='machines.catalog', verbose_name='Модель двигателя')),
                ('equipment_model', models.ForeignKey(limit_choices_to={'entity': 'EQ_M'}, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_machines', to='machines.catalog', verbose_name='Модель техники')),
                ('service_company', models.ForeignKey(limit_choices_to={'role': 'S'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_service', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('transmission_model', models.ForeignKey(limit_choices_to={'entity': 'TR_M'}, on_delete=django.db.models.deletion.PROTECT, related_name='transmission_machines', to='machines.catalog', verbose_name='Модель трансмиссии')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата ТО')),
                ('production', models.IntegerField(verbose_name='Наработка м/час')),
                ('work_order_number', models.CharField(max_length=128, verbose_name='Номер заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance', to='machines.machine', verbose_name='Машина')),
                ('maintenance_carry_out', models.ForeignKey(limit_choices_to={'role': 'S'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_as_carry_out', to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО')),
                ('service_company', models.ForeignKey(limit_choices_to={'role': 'S'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_as_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('type', models.ForeignKey(limit_choices_to={'entity': 'MN_T'}, on_delete=django.db.models.deletion.PROTECT, related_name='type_maintenance', to='machines.catalog', verbose_name='Вид ТО')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('production', models.IntegerField(verbose_name='Наработка м/час')),
                ('failure_description', models.CharField(max_length=256, verbose_name='Описание отказа')),
                ('spare_parts', models.CharField(max_length=256, verbose_name='Запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(verbose_name='Время простоя')),
                ('failure_node', models.ForeignKey(limit_choices_to={'entity': 'FAIL'}, on_delete=django.db.models.deletion.PROTECT, related_name='reclamation_failure_node', to='machines.catalog', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='machines.machine', verbose_name='Машина')),
                ('recovery_method', models.ForeignKey(limit_choices_to={'entity': 'RE_M'}, on_delete=django.db.models.deletion.PROTECT, related_name='reclamation_recovery_method', to='machines.catalog', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(limit_choices_to={'role': 'S'}, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
        ),
    ]
