# Generated by Django 5.1.1 on 2024-09-14 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_client_alter_machine_consignee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='additional_equipment',
            field=models.TextField(null=True, verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'C'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='consignee',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Грузополучатель'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес поставки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'S'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_service', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='supply_contract_number_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Договор поставки номер, дата'),
        ),
    ]
