# Generated by Django 5.1.1 on 2024-09-27 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machine_additional_equipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_carry_out',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'S'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_as_carry_out', to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО'),
        ),
    ]
