# Generated by Django 5.1.1 on 2024-10-01 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_alter_maintenance_maintenance_carry_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='additional_equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'S'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_as_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='service_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'S'}, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
